import FWCore.ParameterSet.Config as cms

hiEvtPlane = cms.EDProducer("EvtPlaneProducer",
                            vertexTag = cms.InputTag("offlinePrimaryVerticesRecovery"),
                            caloTag = cms.InputTag("towerMaker"),
                            castorTag = cms.InputTag("CastorTowerReco"),
                            trackTag = cms.InputTag("generalTracks"),
                            centralityBinTag = cms.InputTag("centralityBin","HFtowers"),
                            centralityVariable = cms.string("HFtowers"),
                            nonDefaultGlauberModel = cms.string(""),
                            loadDB = cms.bool(False),
                            minet = cms.double(0.01),
                            maxet = cms.double(-1),
                            minpt = cms.double(0.5),
                            maxpt = cms.double(3.0),
                            minvtx = cms.double(-15.),
                            maxvtx = cms.double(15.),
                            flatnvtxbins = cms.int32(10),
                            flatminvtx = cms.double(-15.0),
                            flatdelvtx = cms.double(3.0),
                            dzdzerror_ = cms.double(3.0),
                            d0d0error_ = cms.double(3.0),
                            pterror_ = cms.double(0.1),
                            chi2perlayer_ = cms.double(0.18),
                            dzerr = cms.double(10.),
                            dzdzerror_pix_ = cms.double(40.),
                            chi2 = cms.double(40.),
                            FlatOrder = cms.int32(9),
                            NumFlatBins = cms.int32(40),
                            caloCentRef = cms.double(-1),
                            caloCentRefWidth = cms.double(-1),
                            CentBinCompression = cms.int32(5)
                            )
